name: urjob
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: 'none'

# App version
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.7.2

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.3
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  google_fonts: ^6.2.1

# Dev-only dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific settings
flutter:

  # Enable Material Design icons
  uses-material-design: true

  # Asset directory
  assets:
    - images/

  # Example custom fonts (if you add them later)
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
