// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPxhzmTie_ysPIMyB9Ivix5BHMetyZWxs',
    appId: '1:20098166270:web:03d1f1ccd4a6b2756964af',
    messagingSenderId: '20098166270',
    projectId: 'plmo-c5ddd',
    authDomain: 'plmo-c5ddd.firebaseapp.com',
    storageBucket: 'plmo-c5ddd.appspot.com',
    measurementId: 'G-122VPG92TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV5PY1EFNs448uJ7blPkNt60nzVynNBic',
    appId: '1:20098166270:android:d135fb04d1f279906964af',
    messagingSenderId: '20098166270',
    projectId: 'plmo-c5ddd',
    storageBucket: 'plmo-c5ddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8_Pp3OYGrgu3AF94zTjmEzCkbOfonos',
    appId: '1:20098166270:ios:da27490c57f12bcd6964af',
    messagingSenderId: '20098166270',
    projectId: 'plmo-c5ddd',
    storageBucket: 'plmo-c5ddd.appspot.com',
    iosBundleId: 'com.example.urjob',
  );
}
